### ISSUE TITLE
create spreadsheet with xbee to cell version mapping

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#10]
See the version mapping tab:

https://docs.google.com/spreadsheets/d/10OW6EFgvvggHuP6uo2J_35ZiQDwUKKmSnLptmN7VP5s/edit#gid=786798945

**Comment by williamcodes** [comment]
@hrldcpr can you provide a list of which xbee IDs are assigned to hubs and which ones are assigned to cells? I can but them in the spreadsheet if you give me a data dump. To do the mapping for v0.3 and v0.5 cells, I need to know which ones are hubs. That way, I can mark the v0.5 ones and everything else will be v0.3.

**Comment by hrldcpr** [comment]
We've never recorded whether xbees are cells or hubs, and we still don't really need to — we know an xbee is a cell if we get a reading from it, so all we have to know at that point is whether it's on a new board or not.

In other words, if you just mark all of the xbees that are in v0.5 cells, that is the only info we need. (Or vice-versa if you mark all the xbees that are in old v0.3 cells, since in theory those will slowly go away / in the long term they are the "special case".)

**Comment by williamcodes** [comment]
I've marked all the v0.5 cells on the second tab of the [xbee id spreadsheet](https://docs.google.com/spreadsheets/d/10OW6EFgvvggHuP6uo2J_35ZiQDwUKKmSnLptmN7VP5s/edit#gid=786798945).
