### ISSUE TITLE
stuck on step 8 of setting up a hub from scratch

### ISSUE THREAD

**Issue by williamcodes** [heatseeknyc/firmware#3]
The second time I run the `build.sh` script, I am prompted to create ssh keys. When I do, it then tries to ssh into the relay. However, its public keys are not yet on the relay server, so it fails. I dug around the relay server looking for where all the pi ssh keys are stored to see if I could do it manually, but couldn't find them.

**Comment by hrldcpr** [comment]
Yeah, there's a lot of TODOs in that part of the script, since it's sort of a one-time thing.

If you look on an existing hub you can find the keys, in `/root/.ssh/`. We can't store them publicly (e.g. on github) which makes it annoying to build in to this script. Alternatively we can generate and copy new keys to the relay whenever we build a new image (which is what the script is trying to do) but that could get confusing. But yeah if you copy the key from an existing π then you can just not run `ssh-keygen` and `ssh-copy-id`.

Of course, once you succeed at running all this stuff, you'll just end up with the image that we already have :hear_no_evil:

**Comment by hrldcpr** [comment]
I think this is a valid issue :open_mouth:

**Comment by hrldcpr** [comment]
The `build.sh` script is much improved now, and fixes this.
